openapi: 3.0.0
info:
  title: Fragrance Finder API
  version: 1.0.0
  description: API documentation for the Fragrance Finder project

servers:
  - url: http://localhost:3000

paths:
  /api/scrape:
    post:
      summary: Scrape a fragrance URL and find dupes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://example.com/fragrance"
      responses:
        "200":
          description: A structured result of the scraped fragrance and its dupe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FragranceDupeResponse"

        "400":
          description: Invalid input (e.g. malformed URL or empty body)

        "404":
          description: The URL could not be reached or scraped

        "422":
          description: Page was not determined to be a fragrance

        "500":
          description: LLM analysis failed or internal server error

components:
  schemas:
    FragranceDupeResponse:
      type: object
      properties:
        targetName:
          type: string
          example: "Ocean Storm"
        targetCategory:
          type: string
          example: "masculine"
        targetCopy:
          type: string
          example: "A bold aquatic scent inspired by the raw power of crashing waves."
        targetImage:
          type: string
          format: uri
          example: "https://example.com/images/ocean-storm.jpg"
        targetPrice:
          type: string
          example: "$89.99"
        dupeName:
          type: string
          example: "Blue Breeze"
        dupeCategory:
          type: string
          example: "masculine"
        dupeLink:
          type: string
          format: uri
          example: "https://cheapscents.com/blue-breeze"
        dupeBrand:
          type: string
          example: "BudgetScents"
        dupeCopy:
          type: string
          example: "Blue Breeze offers a crisp and clean scent at a fraction of the designer price."
        dupeImage:
          type: string
          format: uri
          example: "https://cheapscents.com/images/blue-breeze.jpg"
        dupePrice:
          type: string
          example: "$19.99"
