# backend/docker/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    container_name: fragrancefinder-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fragrancefinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
